### ISSUE TITLE
Como funciona?

### ISSUE THREAD

**Issue by GuiSelair** [Lucasmg37/spotify-alarm-clock#3]
Salve Salve mano! Curti pakas a ideia! Como funciona? Ta em produção ainda ou já ta finalizado? 😄

**Comment by Lucasmg37** [comment]
Opa @GuiSelair.
A ideia seria automatizar execuções de músicas no spotify.
É possível selecionar o dispositivo onde a track será executada e agendar o horário como um despertador tradicional.
Tá em PROD mas ainda não tá finalizado, na verdade dei uma parada, porque encontrei alguns impedimentos que não encontrei formas de resolver ainda.
Estou usando a API do spotify para iniciar a reprodução, porém para a reprodução iniciar, eu preciso que o dispositivo esteje ativo. Em meus testes iniciais, funciona bem, porém para o meu proposito, que era execução em dispotivos Alexa, não rolou. Na teoria a Alexa está sempre com o spotify "conectado" porém ela não responde aos comandos por api, ela só responde se já estiver reproduzindo algo no instante. 😓

**Comment by GuiSelair** [comment]
Cara! Que show! Curti muito! Eu posso dar uma olhada e fazer um fork pra talvez te ajudar? Achei massa o projeto! Eu utilizaria muito kkkk
